2025-02-15 19:54:18,428 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,431 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,431 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,432 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,432 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,432 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,433 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,433 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,434 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,434 - services.py - WARNING: Дата операции отличается от запроса
2025-02-15 19:54:18,438 - services.py - ERROR: Передан неверный тип данных
2025-02-15 19:54:18,443 - services.py - ERROR: Передан неверный тип данных
2025-02-15 19:54:18,470 - utils.py - WARNING: Файл по переданному пути отсутствует
2025-02-15 19:54:18,477 - utils.py - WARNING: Данные в файле отсутствуют или не являются DataFrame
2025-02-15 19:54:18,484 - utils.py - WARNING: Файл по переданному пути отсутствует
2025-02-15 19:54:18,506 - utils.py - ERROR: Невозможно декодировать JSON данные из файла. Возможная причина: Expecting value: line 1 column 1 (char 0)
2025-02-15 19:54:18,514 - utils.py - ERROR: Ключ не найден
2025-02-15 19:54:18,521 - utils.py - ERROR: Невозможно получить необходимые данные Возможная ошибка: [Errno 2] No such file or directory: ''
2025-02-15 19:54:18,533 - utils.py - ERROR: Невозможно получить необходимые данные Возможная ошибка: [Errno 2] No such file or directory: ''
2025-02-15 19:54:18,542 - utils.py - ERROR: Невозможно декодировать JSON данные из файла. Возможная причина: Expecting value: line 1 column 1 (char 0)
2025-02-15 19:54:18,556 - utils.py - ERROR: Статус код не равен 200. Возможная ошибка: <MagicMock name='get().reason' id='1887808959696'>
2025-02-15 19:54:18,563 - utils.py - ERROR: Необходимый ключ не найден
2025-02-15 19:54:18,574 - utils.py - ERROR: Необходимый ключ не найден
2025-02-15 19:54:18,580 - utils.py - ERROR: Статус код не равен 200. Возможная ошибка: <MagicMock name='get().reason' id='1887808961712'>
2025-02-15 19:54:18,607 - views.py - ERROR: Передано неверное время
2025-02-15 19:54:18,611 - views.py - ERROR: Передано неверное время
2025-02-15 19:54:18,617 - views.py - ERROR: Передано неверное время
2025-02-15 19:54:18,622 - views.py - ERROR: Передано неверное время
2025-02-15 19:54:18,627 - views.py - ERROR: Передано неверное время
2025-02-15 19:54:18,639 - views.py - WARNING: Введена неверная дата
2025-02-15 19:54:18,644 - views.py - WARNING: Введена неверная дата
2025-02-15 19:54:18,650 - views.py - WARNING: Введена неверная дата
